# --------------------------------------
# Hexo Butterfly Theme Configuration
# --------------------------------------

# 导航设置
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fas fa-heart

# 网站图标
favicon: /img/favicon.png

# 代码块设置
highlight_theme: mac light
highlight_copy: true
highlight_lang: true
highlight_shrink: false
highlight_height_limit: 200

# 社交图标
social:
  fab fa-github: https://github.com/johnsmithsren || Github
  fas fa-envelope: mailto:your-email@example.com || Email

# 文章版权
post_copyright:
  enable: true
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 侧边栏设置
aside:
  enable: true
  mobile: true
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: '生活就像青春恋爱物语，总是充满了意外'
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/johnsmithsren
  card_announcement:
    enable: true
    content: 欢迎来到我的博客！
  card_recent_post:
    enable: true
    limit: 5
    sort: date
  card_categories:
    enable: true
    limit: 8
    expand: none
  card_tags:
    enable: true
    limit: 40
    color: true
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8

# 页脚设置
footer:
  owner:
    enable: true
    since: 2020
  custom_text: 
  copyright: true

# 动画效果
animate:
  enable: true
  title_effect: true
  sidebar_effect: true

# 暗黑模式
darkmode:
  enable: true
  button: true
  autoChangeMode: false

# 页面加载动画
preloader:
  enable: true
  source: 1

# 访问统计
busuanzi:
  site_uv: true
  site_uv_header: <i class="fas fa-user"></i> 访客数
  site_uv_footer: 人
  site_pv: true
  site_pv_header: <i class="fas fa-eye"></i> 总访问量
  site_pv_footer: 次
  page_pv: true
  page_pv_header: <i class="fas fa-file-alt"></i> 阅读数
  page_pv_footer: 次
