name: Deploy Blog

on:
  push:
    branches:
      - main # 触发条件：当推送到 main 分支时

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 检出代码

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # 设置 Node.js 版本（根据需要调整）

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install # 安装依赖（如果有的话）

      - name: Configure Git
        run: |
          git config --global user.email "rjm1149104294@outlook.com"
          git config --global user.name "johnsmithsren"
          git remote set-url origin https://x-access-token:${{ secrets.DEPLOYBLOG }}@github.com/johnsmithsren/renjmBlog.github.io.git

      - name: Run deploy script
        run: bash deploy.sh # 执行部署脚本
